### ISSUE TITLE
about evaluate FLD on my own data

### ISSUE THREAD

**Issue by Danee-wawawa** [marcojira/fls#6]
Thank you for your work. I want to evaluate FLD on my own data. 
My current task is to convert visible light images to infrared images, and the data is unpaired. Is your method suitable for evaluating the generated infrared images? If applicable, how are train set, test set, and gen set constructed?
Looking forward to your answer.

**Comment by Danee-wawawa** [comment]
In addition, how to write code in this way? 
<img width="636" alt="1705459933368" src="https://github.com/marcojira/fld/assets/24379250/b6f772a0-28cf-4000-aba6-e8ed4ce32a3a">
Is it to directly replace test_feat in  "fld_val = FLD().compute_metric(train_feat, test_feat, gen_feat)"   with part of train_feat?

**Comment by marcojira** [comment]
Do you have a set of reference infrared images (i.e. what you'd train on)? If so, you should split into train and test sets and use those as train/test feats. For the generated features, you should get them from a set of images generated by your model!

**Comment by Danee-wawawa** [comment]
OK, I'll try it, thank you~

**Comment by Danee-wawawa** [comment]
In order to evaluate FLD, how many training images, test images and generated images are needed at least?

**Comment by marcojira** [comment]
Ideally 10k gen, >10k train and >1k test but you could probably get away with less than that.

**Comment by Danee-wawawa** [comment]
OK, thank you~
